use crate::TransportError;

/// Wire-level operation identifiers for client requests.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Opcode {
    Auth = 0x01,
    Ping = 0x02,
    Get = 0x03,
    GetDel = 0x04,
    GetEx = 0x05,
    Set = 0x06,
    SetNx = 0x07,
    Delete = 0x08,
    Exists = 0x09,
    MGet = 0x0A,
    MSet = 0x0B,
    Incr = 0x0C,
    Decr = 0x0D,
    Expire = 0x0E,
    Ttl = 0x0F,
    Persist = 0x10,
    Rename = 0x11,
    RenameNx = 0x12,
    Scan = 0x13,
    DbSize = 0x14,
    Info = 0x15,
    Metrics = 0x16,
    List = 0x17,
    Clear = 0x18,
    Count = 0x19,
    Save = 0x1A,
    Snapshot = 0x1B,
    Multi = 0x1C,
    Exec = 0x1D,
    Discard = 0x1E,
    Backup = 0x1F,
    Restore = 0x20,
    CreateUser = 0x21,
    DropUser = 0x22,
    CreateRole = 0x23,
    DropRole = 0x24,
    GrantRole = 0x25,
    RevokeRole = 0x26,
    GrantPermission = 0x27,
    RevokePermission = 0x28,
    ShowUsers = 0x29,
    ShowRoles = 0x2A,
    WhoAmI = 0x2B,
    BackupTo = 0x2C,
    RestoreFrom = 0x2D,
    RestoreCheck = 0x2E,
    RestoreCheckFrom = 0x2F,
    AlterUserPassword = 0x30,
    MetricsProm = 0x31,
    BackupVerify = 0x32,
    BackupVerifyFrom = 0x33,
    ShowGrants = 0x34,
    ShowGrantsForUser = 0x35,
    ShowGrantsForRole = 0x36,
    MaintenanceOn = 0x37,
    MaintenanceOff = 0x38,
    MaintenanceStatus = 0x39,
    Health = 0x3A,
    ShowCluster = 0x3B,
    ClusterJoin = 0x3C,
    ClusterRemove = 0x3D,
    ShowReplication = 0x3E,
    PromoteFollower = 0x3F,
    PauseReplication = 0x40,
    ResumeReplication = 0x41,
    ReplicationStatus = 0x42,
    ReplicationSnapshot = 0x43,
    ReplicationFetch = 0x44,
    ReplicationAck = 0x45,
    ReplicationVote = 0x46,
    ReplicationHeartbeat = 0x47,
    ReplicationAppend = 0x48,
    ReplicationInstallSnapshot = 0x49,
}

impl From<Opcode> for u8 {
    fn from(value: Opcode) -> Self {
        value as u8
    }
}

impl TryFrom<u8> for Opcode {
    type Error = TransportError;

    fn try_from(value: u8) -> std::result::Result<Self, Self::Error> {
        match value {
            0x01 => Ok(Self::Auth),
            0x02 => Ok(Self::Ping),
            0x03 => Ok(Self::Get),
            0x04 => Ok(Self::GetDel),
            0x05 => Ok(Self::GetEx),
            0x06 => Ok(Self::Set),
            0x07 => Ok(Self::SetNx),
            0x08 => Ok(Self::Delete),
            0x09 => Ok(Self::Exists),
            0x0A => Ok(Self::MGet),
            0x0B => Ok(Self::MSet),
            0x0C => Ok(Self::Incr),
            0x0D => Ok(Self::Decr),
            0x0E => Ok(Self::Expire),
            0x0F => Ok(Self::Ttl),
            0x10 => Ok(Self::Persist),
            0x11 => Ok(Self::Rename),
            0x12 => Ok(Self::RenameNx),
            0x13 => Ok(Self::Scan),
            0x14 => Ok(Self::DbSize),
            0x15 => Ok(Self::Info),
            0x16 => Ok(Self::Metrics),
            0x17 => Ok(Self::List),
            0x18 => Ok(Self::Clear),
            0x19 => Ok(Self::Count),
            0x1A => Ok(Self::Save),
            0x1B => Ok(Self::Snapshot),
            0x1C => Ok(Self::Multi),
            0x1D => Ok(Self::Exec),
            0x1E => Ok(Self::Discard),
            0x1F => Ok(Self::Backup),
            0x20 => Ok(Self::Restore),
            0x21 => Ok(Self::CreateUser),
            0x22 => Ok(Self::DropUser),
            0x23 => Ok(Self::CreateRole),
            0x24 => Ok(Self::DropRole),
            0x25 => Ok(Self::GrantRole),
            0x26 => Ok(Self::RevokeRole),
            0x27 => Ok(Self::GrantPermission),
            0x28 => Ok(Self::RevokePermission),
            0x29 => Ok(Self::ShowUsers),
            0x2A => Ok(Self::ShowRoles),
            0x2B => Ok(Self::WhoAmI),
            0x2C => Ok(Self::BackupTo),
            0x2D => Ok(Self::RestoreFrom),
            0x2E => Ok(Self::RestoreCheck),
            0x2F => Ok(Self::RestoreCheckFrom),
            0x30 => Ok(Self::AlterUserPassword),
            0x31 => Ok(Self::MetricsProm),
            0x32 => Ok(Self::BackupVerify),
            0x33 => Ok(Self::BackupVerifyFrom),
            0x34 => Ok(Self::ShowGrants),
            0x35 => Ok(Self::ShowGrantsForUser),
            0x36 => Ok(Self::ShowGrantsForRole),
            0x37 => Ok(Self::MaintenanceOn),
            0x38 => Ok(Self::MaintenanceOff),
            0x39 => Ok(Self::MaintenanceStatus),
            0x3A => Ok(Self::Health),
            0x3B => Ok(Self::ShowCluster),
            0x3C => Ok(Self::ClusterJoin),
            0x3D => Ok(Self::ClusterRemove),
            0x3E => Ok(Self::ShowReplication),
            0x3F => Ok(Self::PromoteFollower),
            0x40 => Ok(Self::PauseReplication),
            0x41 => Ok(Self::ResumeReplication),
            0x42 => Ok(Self::ReplicationStatus),
            0x43 => Ok(Self::ReplicationSnapshot),
            0x44 => Ok(Self::ReplicationFetch),
            0x45 => Ok(Self::ReplicationAck),
            0x46 => Ok(Self::ReplicationVote),
            0x47 => Ok(Self::ReplicationHeartbeat),
            0x48 => Ok(Self::ReplicationAppend),
            0x49 => Ok(Self::ReplicationInstallSnapshot),
            other => Err(TransportError::UnknownOpcode(other)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::Opcode;
    use crate::TransportError;

    #[test]
    fn converts_all_known_opcodes() {
        let mappings = [
            (0x01, Opcode::Auth),
            (0x02, Opcode::Ping),
            (0x03, Opcode::Get),
            (0x04, Opcode::GetDel),
            (0x05, Opcode::GetEx),
            (0x06, Opcode::Set),
            (0x07, Opcode::SetNx),
            (0x08, Opcode::Delete),
            (0x09, Opcode::Exists),
            (0x0A, Opcode::MGet),
            (0x0B, Opcode::MSet),
            (0x0C, Opcode::Incr),
            (0x0D, Opcode::Decr),
            (0x0E, Opcode::Expire),
            (0x0F, Opcode::Ttl),
            (0x10, Opcode::Persist),
            (0x11, Opcode::Rename),
            (0x12, Opcode::RenameNx),
            (0x13, Opcode::Scan),
            (0x14, Opcode::DbSize),
            (0x15, Opcode::Info),
            (0x16, Opcode::Metrics),
            (0x17, Opcode::List),
            (0x18, Opcode::Clear),
            (0x19, Opcode::Count),
            (0x1A, Opcode::Save),
            (0x1B, Opcode::Snapshot),
            (0x1C, Opcode::Multi),
            (0x1D, Opcode::Exec),
            (0x1E, Opcode::Discard),
            (0x1F, Opcode::Backup),
            (0x20, Opcode::Restore),
            (0x21, Opcode::CreateUser),
            (0x22, Opcode::DropUser),
            (0x23, Opcode::CreateRole),
            (0x24, Opcode::DropRole),
            (0x25, Opcode::GrantRole),
            (0x26, Opcode::RevokeRole),
            (0x27, Opcode::GrantPermission),
            (0x28, Opcode::RevokePermission),
            (0x29, Opcode::ShowUsers),
            (0x2A, Opcode::ShowRoles),
            (0x2B, Opcode::WhoAmI),
            (0x2C, Opcode::BackupTo),
            (0x2D, Opcode::RestoreFrom),
            (0x2E, Opcode::RestoreCheck),
            (0x2F, Opcode::RestoreCheckFrom),
            (0x30, Opcode::AlterUserPassword),
            (0x31, Opcode::MetricsProm),
            (0x32, Opcode::BackupVerify),
            (0x33, Opcode::BackupVerifyFrom),
            (0x34, Opcode::ShowGrants),
            (0x35, Opcode::ShowGrantsForUser),
            (0x36, Opcode::ShowGrantsForRole),
            (0x37, Opcode::MaintenanceOn),
            (0x38, Opcode::MaintenanceOff),
            (0x39, Opcode::MaintenanceStatus),
            (0x3A, Opcode::Health),
            (0x3B, Opcode::ShowCluster),
            (0x3C, Opcode::ClusterJoin),
            (0x3D, Opcode::ClusterRemove),
            (0x3E, Opcode::ShowReplication),
            (0x3F, Opcode::PromoteFollower),
            (0x40, Opcode::PauseReplication),
            (0x41, Opcode::ResumeReplication),
            (0x42, Opcode::ReplicationStatus),
            (0x43, Opcode::ReplicationSnapshot),
            (0x44, Opcode::ReplicationFetch),
            (0x45, Opcode::ReplicationAck),
            (0x46, Opcode::ReplicationVote),
            (0x47, Opcode::ReplicationHeartbeat),
            (0x48, Opcode::ReplicationAppend),
            (0x49, Opcode::ReplicationInstallSnapshot),
        ];

        for (byte, opcode) in mappings {
            assert_eq!(Opcode::try_from(byte).unwrap(), opcode);
            assert_eq!(u8::from(opcode), byte);
        }
    }

    #[test]
    fn rejects_unknown_opcode() {
        assert!(matches!(
            Opcode::try_from(0xff),
            Err(TransportError::UnknownOpcode(0xff))
        ));
    }
}
